//go:build ignore
// +build ignore

package main

import (
	"encoding/json"
	"fmt"
	"os"
)

// processFile 读取文件内容并将其转换为安全的 JSON 字符串
func processFile(filename string) (string, error) {
	fileContentBytes, err := os.ReadFile(filename)
	if err != nil {
		return "", fmt.Errorf("error reading %s: %w", filename, err)
	}

	escapedContent, err := json.Marshal(string(fileContentBytes))
	if err != nil {
		return "", fmt.Errorf("error escaping content from %s: %w", filename, err)
	}

	return string(escapedContent), nil
}

func main() {
	// 1. 处理 customize_head.html
	headContent, err := processFile("customize_head.html")
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}

	// 2. 处理 customize_body.html
	bodyContent, err := processFile("customize_body.html")
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}

	// 3. 创建要生成的 Go 文件
	outputFile, err := os.Create("generated_custom.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating generated_custom.go: %v\n", err)
		os.Exit(1)
	}
	defer outputFile.Close()

	// 4. 写入 Go 代码，包含两个常量
	fmt.Fprintf(outputFile, `// Code generated by go run customize_generator.go; DO NOT EDIT.
package data

const CustomizeHeadContent = %s

const CustomizeBodyContent = %s
`, headContent, bodyContent)

	fmt.Println("Successfully generated generated_custom.go")
}
